server: 
    port: 8091
    context-path: /exam
spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/examination?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf: 
      cache: true        
    devtools: 
      restart: 
        enabled: true
        
mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-locations: classpath:mybatis.xml
    type-aliases-package: com.oxy.model
    
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.oxy.dao: debug
    com.oxy.dao.ext: debug
    
single:
  template:
    path: templates/SingleTemplate.xlsx
    
SAQ:
  template:
    path: templates/SAQTemplate.xlsx

student:
  template:
    path: templates/StudentTemplate.xlsx
score:
  template:
    path: templates/ScoreTemplate.xlsx

#  mapper-locations=classpath: mapper/*.xml 
